import {StyleSheet} from 'react-native';
let _defz = require('../../com/def');

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    position: 'relative',
    backgroundColor: '#000',
  },
  scrollViewH2: {
    position: 'absolute',
    bottom: _defz.height / 8,
    left: 0,
    zIndex: 99999999,
  },
  searchTypeText: {
    fontFamily: 'FuturaPT-Medium',
    fontSize: 18,
    color: '#707070',
  },
  searchTypeTextActive: {
    fontFamily: 'FuturaPT-Medium',
    fontSize: 18,
    color: '#3D80F2',
  },
  touch_style_close: {
    backgroundColor: '#F0F0F0',
    marginLeft: _defz.width / 15,
    borderRadius: 10,
    width: _defz.width / 2,
    marginTop: 'auto',
  },
  touch_style_open: {
    backgroundColor: 'white',
    marginLeft: _defz.width / 15,
    borderRadius: 10,
    width: _defz.width / 2,
    marginTop: 'auto',
  },
  text_borrow: {
    fontSize: 13,
    color: 'gray',
    marginLeft: '9%',
  },
  sliderImages: {
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    maxWidth: '100%',
    height: _defz.height / 6,
  },
  text_address: {
    marginLeft: '5%',
    marginTop: 2,
    fontSize: 10,
  },
  text_title_shop: {
    marginLeft: 5,
    marginTop: 5,
    fontSize: 18,
  },
  text_title_shop_number: {
    marginLeft: 5,
    marginTop: 8,
    fontSize: 14,
  },
  view_line: {
    width: '70%',
    alignSelf: 'center',
    height: 5,
    borderRadius: 15,
    marginTop: 5,
    backgroundColor: 'black',
  },
  view_line_b: {
    width: '70%',
    alignSelf: 'center',
    height: 4,
    borderRadius: 15,
    marginTop: 5,
    backgroundColor: 'black',
    position: 'absolute',
    flex: 1,
    zIndex: 999,
  },

  map: {
    marginTop: _defz.height / 15,
    width: _defz.width,
    borderRadius: 100,
    position: 'relative',
    flex: 1,
  },
  transparentHeader: {
    zIndex: 999999,
    alignSelf: 'center',
    width: '100%',
    height: '100%',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    position: 'absolute',
    top: _defz.height / 30.5,
  },
  view_line_b: {
    width: '50%',
    alignSelf: 'center',
    height: 2,
    borderRadius: 15,
    marginTop: '5%',
    backgroundColor: 'black',
    position: 'absolute',
    zIndex: 999,
  },
  footer: {
    width: '100%',
    paddingLeft: 20,
    paddingRight: 20,
    height: _defz.height / 10,
    borderTopColor: '#C3BCBC',
    backgroundColor: '#fff',
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flex: 1,
  },
  searchBox: {
    width: '70%',
    position: 'relative',
    left: _defz.width / 15,
    bottom: _defz.height / 70,
  },
  footerSearchInput: {
    borderColor: '#3D80F2',
    borderWidth: 2,
    width: '100%',
    borderRadius: 30,
    textAlign: 'center',
    color: '#3D80F2',
  },
  searchImage: {
    position: 'absolute',
    left: 20,
    bottom: 15,
  },
  homeButton: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: _defz.height / 40,
  },
  headerBackButton: {
    width: '40%',
    height: 10,
    backgroundColor: '#000',
    borderRadius: 50,
    marginTop: '6%',
    alignSelf: 'center',
  },
  mapHeaderBackButton: {
    width: '40%',
    height: 10,
    backgroundColor: '#000',
    borderRadius: 50,
    marginTop: '12%',
    alignSelf: 'center',
  },
  content: {
    width: '100%',
    height: '100%',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    position: 'absolute',
    top: _defz.height / 13.5,
    marginBottom: _defz.height / 3,
    backgroundColor: '#F0F0F0',
  },
  contentTransparent: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    backgroundColor: '#000',
  },
  searchBoxTop: {
    width: '100%',
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchInput: {
    width: '90%',
    alignSelf: 'center',
    borderColor: '#C3BCBC',
    borderWidth: 1,
    padding: '2%',
    marginTop: '2%',
    borderRadius: 40,
    elevation: 2,
    textAlign: 'center',
  },
  productCards: {
    width: '100%',
    position: 'absolute',
    top: _defz.height / 4,
    flex: 1,
    paddingRight: '2%',
    paddingLeft: '2%',
  },
  scrollViewV: {
    width: '100%',
    height: _defz.height / 1.3,
    marginTop: _defz.height / 25,
  },
  products: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
  },
  searchTypeButtons: {
    width: '50%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#F0F0F0',
    elevation: 3,
    marginTop: '4%',
    paddingHorizontal: '1%',
    borderRadius: 50,
    height: _defz.height / 27,
  },
  searchTypeButton: {
    marginTop: -5,
  },
  searchTypeButtonActive: {
    borderWidth: 1.5,
    borderColor: '#3D80F2',
    borderRadius: 50,
    paddingHorizontal: '3%',
    width: _defz.width / 5,
    height: _defz.height / 30,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 2,
    backgroundColor: '#fff',
  },
  header: {
    backgroundColor: 'transparent',
    width: '90%',
    alignSelf: 'center',
    borderRadius: 30,
    marginTop: -_defz.height / 400,
  },
  search_input: {
    color: 'gray',
    fontFamily: 'FuturaPTDemi',
    fontSize: 13,
    borderRadius: 15,
  },
});
